name: Build juicefs image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
#  push:
#    branches:
#      - docker_build

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login Docker Hub
      run: docker login registry.cn-hangzhou.aliyuncs.com --username zww@hdls.me --password ${{ secrets.ACR_TOKEN }}
    - name: check latest tag
      continue-on-error: true
      run: |
       JUICEFS_CE_LATEST_VERSION=$(curl -fsSL https://api.github.com/repos/juicedata/juicefs/releases/latest | grep tag_name | grep -oE 'v[0-9]+\.[0-9][0-9]*(\.[0-9]+(-[0-9a-z]+)?)?')
       JUICEFS_EE_LATEST_VERSION=$(curl -sSL https://juicefs.com/static/juicefs -o juicefs-ee && chmod +x juicefs-ee && ./juicefs-ee version | cut -d' ' -f3)
       echo "MOUNT_IMAGE_EXIST=false" >> $GITHUB_ENV
       echo "mount image is registry.cn-hangzhou.aliyuncs.com/juicefs/juicefs-fuse:${JUICEFS_CE_LATEST_VERSION}-$JUICEFS_EE_LATEST_VERSION"
       docker pull registry.cn-hangzhou.aliyuncs.com/juicefs/juicefs-fuse:${JUICEFS_CE_LATEST_VERSION}-$JUICEFS_EE_LATEST_VERSION
       rst=$?
       if [ $rst -eq 0 ]; then
         echo "MOUNT_IMAGE_EXIST=true" >> $GITHUB_ENV
       fi
    - name: Buildx and Push docker image
      run: |
        image_exist=${{ env.MOUNT_IMAGE_EXIST }}
        if [ $image_exist == "false" ]; then
          echo "Build JuiceFS version image"
          make juicefs-image-version
        else
          echo "JuiceFS FUSE version image already exists"
        fi
    - name: sync image
      env:
        ACR_TOKEN: ${{ secrets.ACR_TOKEN }}
      run: |
        image_exist=${{ env.MOUNT_IMAGE_EXIST }}
        if [ $image_exist == "false" ]; then
          echo "Sync JuiceFS version image"
          cd ${GITHUB_WORKSPACE}/.github/scripts/
          ./sync.sh
        else
          echo "JuiceFS FUSE version image already exists"
        fi
