name: Build juicefs image

on:
  workflow_dispatch:
#  push:
#    branches:
#      - docker_build

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login Docker Hub
      run: docker login registry.cn-hangzhou.aliyuncs.com --username zww@hdls.me --password ${{ secrets.ACR_TOKEN }}
    - name: Buildx and Push docker image
      run: |
        make juicefs-image-version
    - name: sync image
      env:
        JUICEFS_LATEST_VERSION: $(shell curl -fsSL https://api.github.com/repos/juicedata/juicefs/releases/latest | grep tag_name | grep -oE 'v[0-9]+\.[0-9][0-9]*(\.[0-9]+(-[0-9a-z]+)?)?')
        ACR_TOKEN: ${{ secrets.ACR_TOKEN }}
      run: |
        cd ${GITHUB_WORKSPACE}/.github/scripts/
        ./sync.sh
